#### crowsnest.conf
#### This is the default config after installation.
#### It is also used as the default config in MainsailOS.
#### For details on how to configure this to your needs, see:
#### https://github.com/mainsail-crew/crowsnest/blob/master/README.md


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
####    Note: These ports are default for most Mainsail         #####
####    installations. Using any other port would involve       #####
####    changing the proxy configuration or using URLs          #####
####    with the specific port like                             #####
####    http://<ip>:<port>/?action=[stream/snapshot]            #####
####                                                            #####
#####################################################################
####    RTSP Stream URL: ( if enabled and supported )           #####
####    rtsp://<ip>:<rtsp_port>/stream.h264                     #####
#####################################################################



[crowsnest]
log_path: ~/printer_data/logs/crowsnest.log
log_level: verbose                      # Auf 'quiet' stellen, wenn alles läuft

[cam 1]
mode: camera-streamer                 # Bester Modus für Raspi-Cams ab 2025
enable_rtsp: false                   # Brauchst du nur für externe Apps
port: 8080                              # Der Port für den Stream
device: /base/soc/i2c0mux/i2c@1/ov5647@36              # Hier den Pfad aus v4l2-ctl eintragen
resolution: 640x480                    # Höhere Auflösung bei v1.3 Cam oft ruckelig
max_fps: 15                             # 15 FPS schont die CPU deines Pi
#v4l2ctl: focus_absolute=0